import { PubSub } from "graphql-subscriptions";

export const pubsub: PubSub = new PubSub();

export const EVENTS = {
  POST_CREATED: "POST_CREATED",
  COMMENT_ADDED: "COMMENT_ADDED",
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_SENT_TO_USER: "MESSAGE_SENT_TO_USER",
  MESSAGE_READ: "MESSAGE_READ",
  CHAT_PERMISSION_UPDATED: "CHAT_PERMISSION_UPDATED",
  LIKE_TOGGLED: "LIKE_TOGGLED",
  USER_TYPING: "USER_TYPING",
  GROUP_MESSAGE_SENT: "GROUP_MESSAGE_SENT",
  MEETING_SIGNAL: "MEETING_SIGNAL",
  MEETING_UPDATED: "MEETING_UPDATED",
  MEETING_INVITED: "MEETING_INVITED",
} as const;

export type EventName = (typeof EVENTS)[keyof typeof EVENTS];
